# Generated by Django 4.2.3 on 2024-07-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='customer_information_file_number',
            new_name='GST_NUMBER',
        ),
    ]
